### PR TITLE
Classify polygon rings to distinguish inner polygon rings and multipolygons

### PR DESCRIPTION
**Pull request by jfirebaugh**
This is a non-semver-major reimplementation of #33 that applies ring classification only in `toGeoJSON`. The structure of the return value of `loadGeometry()` is unchanged.

This is needed for https://github.com/mapbox/mapbox-gl-js/issues/2586.

However, I can't get a GeoJSON Polygon with inner ring to round trip through a mapnik created vector tile. As the failing test here shows, it comes out with ring order indicating a multipolygon. cc @flippmoke @springmeyer @mourner.

### CODE REVIEW

**Comment by mourner** [comment]
What's the reason to keep it non-semver-major now that we have earcut in master + VT2? We could merge #33 instead and then eliminate duplicated `classifyRings` code from gl-js.

**Comment by jfirebaugh** [comment]
mapbox-gl-js depends now on vt-pbf, which would need a coordinated semver major release.

**Comment by mourner** [comment]
@jfirebaugh yeah, sounds good.

**Comment by springmeyer** [comment]
> However, I can't get a GeoJSON Polygon with inner ring to round trip through a mapnik created vector tile. As the failing test here shows, it comes out with ring order indicating a multipolygon. cc @flippmoke @springmeyer @mourner.

Per chat confirmed this is not longer an issue.

**Pull request merged**
