### PR TITLE
Add typings

### PR DESCRIPTION
**Pull request by HarelM**
Adds typings file and updates package.json.

### CODE REVIEW

**Comment by HarelM** [comment]
Any updates on this? I would love to have this merged :-)

**Comment by HarelM** [comment]
@mourner @anandthakker Any chance to merge this?

**Comment by mourner** [comment]
@HarelM sorry, no bandwidth for this in the nearest days. Also note that `vector-tile-js` might see an overhaul in the near future https://github.com/mapbox/vector-tile-js/issues/79 which will require rewriting the types.

**Comment by HarelM** [comment]
Thanks for the info!
I don't mind writing the types again after this change as long as I have a version with these typings :-)

**Comment by mourner** [comment]
Apologies for not merging this at the time. Superceded by #85 which introduces first-class types.

**Pull request closed without merging**
