### PR TITLE
Fix infinite loop when reading closepath command

### LINKED ISSUE #60: Infinite loop when reading polygon close command (7)
Hello,

I discovered a bug that is pretty serious and causes browser to hang. The issue is when reading a geometry that has closepath command represented with number 7.
```javascript
VectorTileFeature.prototype.loadGeometry = function() {
    var pbf = this._pbf;
    pbf.pos = this._geometry;

    var end = pbf.readVarint() + pbf.pos,
        cmd = 1,
        length = 0,
        x = 0,
        y = 0,
        lines = [],
        line;

    while (pbf.pos < end) {
        if (!length) {
            var cmdLen = pbf.readVarint();
            cmd = cmdLen & 0x7;
            length = cmdLen >> 3;
        }

        length--;

        if (cmd === 1 || cmd === 2) {
            x += pbf.readSVarint();
            y += pbf.readSVarint();

            if (cmd === 1) { // moveTo
                if (line) lines.push(line);
                line = [];
            }

            line.push(new Point(x, y));

        } else if (cmd === 7) {

            // Workaround for https://github.com/mapbox/mapnik-vector-tile/issues/90
            if (line) {
                line.push(line[0].clone()); // closePolygon
            }

        } else {
            throw new Error('unknown command ' + cmd);
        }
    }

    if (line) lines.push(line);

    return lines;
};
```

When writing geometry to pbf, if closepath occurs, a 7 will be written to buffer. But when reading a geometry part of .pbf this isn't handled correctly. The following case happens:

When pbf reads 7.
```javascript
if (!length) { // This is 0
            var cmdLen = pbf.readVarint();
            cmd = cmdLen & 0x7; // This is 7
            length = cmdLen >> 3; // length evaluates to 0
        }

length--; // this becomes -1
```
Next iteration length will still be 0
```javascript
if (!length) { // This is -1 and evaluates to false, which skips reading the command
            var cmdLen = pbf.readVarint();
            cmd = cmdLen & 0x7; // This is 7
            length = cmdLen >> 3; // length evaluates to 0
        }

length--; // this becomes -2 
```
And this goes into infinite loop.

This code hasn't changed in a while but the `writeGeometry` in vt-pbf has.
```javascript
function writeGeometry (feature, pbf) {
  var geometry = feature.loadGeometry()
  var type = feature.type
  var x = 0
  var y = 0
  var rings = geometry.length
  for (var r = 0; r < rings; r++) {
    var ring = geometry[r]
    var count = 1
    if (type === 1) {
      count = ring.length
    }
    pbf.writeVarint(command(1, count)) // moveto
    // do not write polygon closing path as lineto
    var lineCount = type === 3 ? ring.length - 1 : ring.length
    for (var i = 0; i < lineCount; i++) {
      if (i === 1 && type !== 1) {
        pbf.writeVarint(command(2, lineCount - 1)) // lineto
      }
      var dx = ring[i].x - x
      var dy = ring[i].y - y
      pbf.writeVarint(zigzag(dx))
      pbf.writeVarint(zigzag(dy))
      x += dx
      y += dy
    }
    if (type === 3) { // this changed recently
      pbf.writeVarint(command(7, 0)) // closepath
    } //
  }
}
```
The type 3 was added only recently. 

The fix is simple: 

Change `if (!length)` to `if (length <= 0)`. And this will allow for length to be negative, thus allowing next command to be read.

### PR DESCRIPTION
**Pull request by sanjin-saric**
Fixes #60

### CODE REVIEW

**Comment by mourner** [comment]
Can you please add a test for this issue?

**Comment by sanjin-saric** [comment]
Sure will do. Test should check state of while loop after reading closepath command?

**Comment by mourner** [comment]
It should exercise `loadGeometry` of a problematic feature, reading it properly instead of freezing.

**Comment by sanjin-saric** [comment]
I will put something together tonight. I have a pbf ready with aforementioned problematic command.

**Comment by mourner** [comment]
Looked into it and I think this is a nice elegant fix. Will merge after there's a test.

**Comment by anandthakker** [comment]
--> #63

**Comment by anandthakker** [comment]
Thanks again, @sanjin-saric -- and my apologies that the commit that went into master was under my name rather than yours (due to the "squash" merge)

**Comment by sanjin-saric** [comment]
No problem, just glad the fix is out, so I can use the official package, not my forked version. Cheers!

**Comment by mourner** [comment]
> commit that went into master was under my name rather than yours (due to the "squash" merge)

FYI GitHub now has a feature for that case: https://blog.github.com/2018-01-29-commit-together-with-co-authors/

**Pull request closed without merging**
